apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-ms1-using-oc
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  params:
    - name: pathToYamlFile
      description: The path to the DeploymentConfig yaml file to customize within the git source
    - name: manifestDir
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag of the images to be used.
      default: "latest"
  steps:
  - name: apply-secret
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/git-source
    command: ["./config/generateSecrets.sh"]
    args:
      - "ace-server-ms1-secret"
  - name: update-yaml
    image: alpine
    command: ["sed"]
    args:
      - "-i"
      - "-e"
      - "s;__IMAGE__;$(inputs.params.imageUrl):$(inputs.params.imageTag);g"
      - "/workspace/git-source/$(inputs.params.pathToYamlFile)"
  - name: run-oc
    image: quay.io/openshift/origin-cli:latest
    command: ["oc"]
    args:
      - "apply"
      - "-f"
      - "/workspace/git-source/$(inputs.params.manifestDir)"