# just attempting to squeeze a buildah in in place into this example that was based on kaniko builder
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  params:
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
      default: "latest"  
    - name: TLSVERIFY
      description: Do not verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "false"

  steps:
  - name: build
    image: quay.io/buildah/stable:v1.11.0
    workingDir: /workspace/git-source
    command: ['buildah', 'bud', '--tls-verify=$(inputs.params.TLSVERIFY)','-t', '$(inputs.params.imageUrl):$(inputs.params.imageTag)','.']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true

  - name: push
    image: quay.io/buildah/stable:v1.11.0
    workingDir: /workspace/source
    command: ['buildah', 'push', '--tls-verify=$(inputs.params.TLSVERIFY)', '$(inputs.params.imageUrl):$(inputs.params.imageTag)','image-registry.openshift-image-registry.svc:5000/ace/ace-cicd-sample-ms1:latest']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  volumes:
  - name: varlibcontainers
    emptyDir: {}