apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ace-ms1-tb
spec:
  params:
  - name: git-repo-url
    value: "https://github.com/$(body.repository.full_name).git"
  - name: git-revision
    value: $(body.head_commit.id)